#!/usr/bin/env python3
"""Monitor tokens generated by the local model server (llama.cpp) on port 13109.

Polls the llama.cpp ``/slots`` endpoint and tracks per-slot deltas of
``n_decoded`` (generated tokens) and ``n_prompt_tokens`` (prompt tokens),
reporting a live token rate, session cumulative totals, and per-slot state.

This works WITHOUT the server being started with ``--metrics``: slot
counters increment while the model generates, so polling deltas gives an
accurate live count.  Tokens generated by a task that starts AND finishes
entirely between two polls are missed (unavoidable without server-side
metrics); at the default 1s interval this is negligible.

Usage:
    python scripts/monitor_local_model_tokens.py
    python scripts/monitor_local_model_tokens.py --once
    python scripts/monitor_local_model_tokens.py --interval 2 --json

Exit: Ctrl+C stops and prints a final summary.  Non-zero exit when the
server is unreachable.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
import urllib.request
from typing import Any, Optional

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 13109
DEFAULT_INTERVAL = 1.0


def fetch_slots(host: str, port: int, timeout: float) -> list[dict[str, Any]]:
    """GET /slots and return the slot array.  Raises on HTTP/network errors."""
    url = f"http://{host}:{port}/slots"
    with urllib.request.urlopen(url, timeout=timeout) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    if not isinstance(data, list):
        raise RuntimeError(f"/slots returned unexpected shape: {type(data).__name__}")
    return data


def slot_state(slot: dict[str, Any]) -> str:
    """Human-readable slot state."""
    if slot.get("is_processing"):
        return "RUNNING"
    nt = slot.get("next_token")
    if isinstance(nt, list) and nt and nt[0].get("has_next_token"):
        return "DECODING"
    return "idle"


def _decoded(slot: dict[str, Any]) -> int:
    """Read n_decoded from the top level or the next_token[0] fallback."""
    value = slot.get("n_decoded")
    if value is None:
        nt = slot.get("next_token")
        if isinstance(nt, list) and nt:
            value = nt[0].get("n_decoded")
    return value or 0


class SlotTracker:
    """Tracks token deltas for one slot across polls."""

    def __init__(self) -> None:
        self.decoded: Optional[int] = None   # last seen n_decoded
        self.prompt: Optional[int] = None    # last seen n_prompt_tokens
        self.task: Optional[int] = None      # last seen id_task
        self.gen_delta: int = 0              # generated tokens this window
        self.prompt_delta: int = 0           # prompt tokens this window
        self.gen_total: int = 0              # generated tokens this session
        self.prompt_total: int = 0           # prompt tokens this session

    def observe(self, slot: dict[str, Any]) -> None:
        decoded = _decoded(slot)
        prompt = slot.get("n_prompt_tokens") or 0
        task = slot.get("id_task")

        if task is not None and self.task is not None and task != self.task:
            # New task started in this slot: the previous task's final
            # decoded count was already captured by an earlier poll, so we
            # simply restart the baseline at the new task's counters.
            self.gen_delta = 0
            self.prompt_delta = 0
        elif self.decoded is not None:
            d = decoded - self.decoded
            if d > 0:
                self.gen_delta += d
                self.gen_total += d
        if self.prompt is not None:
            p = prompt - self.prompt
            if p > 0:
                self.prompt_delta += p
                self.prompt_total += p

        self.decoded = decoded
        self.prompt = prompt
        self.task = task

    def reset_window(self) -> None:
        self.gen_delta = 0
        self.prompt_delta = 0


def render_snapshot(
    trackers: dict[int, SlotTracker],
    slots: list[dict[str, Any]],
    gen_delta: int,
    prompt_delta: int,
    gen_rate: float,
    prompt_rate: float,
    gen_cum: int,
    prompt_cum: int,
    elapsed: float,
    as_json: bool,
) -> str:
    """Render one poll as a JSON line or a human-readable block."""
    if as_json:
        per_slot = []
        for slot in slots:
            per_slot.append({
                "id": slot["id"],
                "state": slot_state(slot),
                "task": slot.get("id_task"),
                "decoded": _decoded(slot),
                "remain": slot.get("next_token", [{}])[0].get("n_remain"),
                "prompt_tokens": slot.get("n_prompt_tokens"),
            })
        return json.dumps({
            "ts": time.strftime("%Y-%m-%dT%H:%M:%S"),
            "elapsed_s": round(elapsed, 2),
            "slots_total": len(slots),
            "slots_busy": sum(1 for s in slots if s.get("is_processing")),
            "generated_tok": gen_delta,
            "generated_tok_s": round(gen_rate, 1),
            "prompt_tok": prompt_delta,
            "prompt_tok_s": round(prompt_rate, 1),
            "generated_cum": gen_cum,
            "prompt_cum": prompt_cum,
            "slots": per_slot,
        })

    lines = [
        f"[{time.strftime('%H:%M:%S')}] slots={len(slots)} busy="
        f"{sum(1 for s in slots if s.get('is_processing'))} | "
        f"gen +{gen_delta} tok ({gen_rate:.1f} tok/s) | "
        f"cum {gen_cum:,} tok | prompt +{prompt_delta} tok | "
        f"cum {prompt_cum:,} tok",
    ]
    for slot in slots:
        t = trackers[slot["id"]]
        remain = slot.get("next_token", [{}])[0].get("n_remain")
        lines.append(
            f"  slot {slot['id']}: task {slot.get('id_task')} "
            f"{slot_state(slot):<8} decoded={_decoded(slot)} "
            f"remain={remain} prompt={slot.get('n_prompt_tokens')} "
            f"gen_win={t.gen_delta}"
        )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Monitor tokens generated by the local model on a llama.cpp server.",
    )
    parser.add_argument("--host", default=DEFAULT_HOST, help=f"server host (default {DEFAULT_HOST})")
    parser.add_argument("--port", type=int, default=DEFAULT_PORT, help=f"server port (default {DEFAULT_PORT})")
    parser.add_argument("--interval", type=float, default=DEFAULT_INTERVAL, help="poll interval seconds (default 1.0)")
    parser.add_argument("--timeout", type=float, default=3.0, help="HTTP timeout per poll (default 3.0)")
    parser.add_argument("--once", action="store_true", help="print one snapshot and exit")
    parser.add_argument("--json", action="store_true", help="emit one JSON line per poll")
    args = parser.parse_args()

    if args.interval <= 0:
        parser.error("--interval must be positive")
    if args.timeout <= 0:
        parser.error("--timeout must be positive")

    trackers: dict[int, SlotTracker] = {}
    start = time.monotonic()
    last_ts = start
    failures = 0

    def summarize() -> None:
        elapsed = time.monotonic() - start
        gen_cum = sum(t.gen_total for t in trackers.values())
        print(
            f"\nTotal: {gen_cum:,} tokens generated in {elapsed:.0f}s "
            f"({gen_cum / elapsed:.1f} tok/s avg) over {len(trackers)} slot(s), "
            f"{failures} failed poll(s)"
        )

    try:
        while True:
            now = time.monotonic()
            try:
                slots = fetch_slots(args.host, args.port, args.timeout)
                failures = 0
            except Exception as exc:  # network/HTTP: report and keep polling
                failures += 1
                print(
                    f"[{time.strftime('%H:%M:%S')}] ERROR: cannot reach "
                    f"http://{args.host}:{args.port}/slots — {exc} "
                    f"({failures} consecutive)",
                    flush=True,
                )
                if args.once:
                    return 1
                time.sleep(args.interval)
                continue

            window = now - last_ts
            window_gen = 0
            window_prompt = 0
            for slot in slots:
                t = trackers.setdefault(slot["id"], SlotTracker())
                t.observe(slot)
                window_gen += t.gen_delta
                window_prompt += t.prompt_delta

            gen_cum = sum(t.gen_total for t in trackers.values())
            prompt_cum = sum(t.prompt_total for t in trackers.values())
            gen_rate = window_gen / window if window > 0 else 0.0
            prompt_rate = window_prompt / window if window > 0 else 0.0
            elapsed = now - start

            if args.json:
                print(render_snapshot(trackers, slots, window_gen, window_prompt, gen_rate, prompt_rate, gen_cum, prompt_cum, elapsed, True), flush=True)
            else:
                print(
                    render_snapshot(trackers, slots, window_gen, window_prompt, gen_rate, prompt_rate, gen_cum, prompt_cum, elapsed, False),
                    end="\r" if not args.once else "\n",
                    flush=True,
                )

            for t in trackers.values():
                t.reset_window()
            last_ts = now

            if args.once:
                return 0
            time.sleep(args.interval)
    except KeyboardInterrupt:
        summarize()
        return 0


if __name__ == "__main__":
    sys.exit(main())
